name: mergen

on:
  issue_comment:
    types: [created]
  pull_request_review_comment:
    types: [created]

jobs:
  mergen:
    if: |
      contains(github.event.comment.body, ' /oc') ||
      startsWith(github.event.comment.body, '/oc') ||
      contains(github.event.comment.body, ' /mergen') ||
      startsWith(github.event.comment.body, '/mergen')
    runs-on: ubuntu-24.04
    permissions:
      id-token: write
      contents: read
      pull-requests: read
      issues: read
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - uses: ./.github/actions/setup-bun

      - name: Run mergen
        uses: TiaMEOWS/mergen/github@latest
        env:
          MERGEN_API_KEY: ${{ secrets.MERGEN_API_KEY }}
          MERGEN_PERMISSION: '{"bash": "deny"}'
        with:
          model: mergen/claude-opus-4-5
